// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MNA_j8JC550BOZpOqb8NkVhBKP2jp3I',
    appId: '1:1026737677534:android:9daefb04b5ebdda5008e4f',
    messagingSenderId: '1026737677534',
    projectId: 'rms-expense-manager',
    storageBucket: 'rms-expense-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQlCs1Vi17HXgiUByeimda5xXXUc6NOE',
    appId: '1:1026737677534:ios:e6e7ae6ba44dce50008e4f',
    messagingSenderId: '1026737677534',
    projectId: 'rms-expense-manager',
    storageBucket: 'rms-expense-manager.firebasestorage.app',
    iosBundleId: 'com.example.rmsExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQlCs1Vi17HXgiUByeimda5xXXUc6NOE',
    appId: '1:1026737677534:ios:e6e7ae6ba44dce50008e4f',
    messagingSenderId: '1026737677534',
    projectId: 'rms-expense-manager',
    storageBucket: 'rms-expense-manager.firebasestorage.app',
    iosBundleId: 'com.example.rmsExpenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALxONB7TqYIk6FhOtYBU4SbmVAQ1Mf0lw',
    appId: '1:1026737677534:web:c35d2c64ec97dbc1008e4f',
    messagingSenderId: '1026737677534',
    projectId: 'rms-expense-manager',
    authDomain: 'rms-expense-manager.firebaseapp.com',
    storageBucket: 'rms-expense-manager.firebasestorage.app',
  );

}